name = jcp
description = HCPRO based layout for JCP
preview = preview.png
template = jcp-layout

; Regions
regions[top]       = Page Top
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[masthead]		= Masthead
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[content_bottom] = Content Bottom
regions[footer]         = Footer
regions[bottom]    = Page Bottom

; Stylesheets
stylesheets[all][] = /sites/justcoding.com/themes/jc/debug/styles/css/jcp.layout.css
