name = hcpro
description = Standard default layout for HCPRO
preview = preview.png
template = hcpro-layout

; Regions
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[masthead]		= Masthead
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[content_bottom] = Content Bottom
regions[footer]         = Footer
